-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 23:15:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Gestão-Produtos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Gestão-Produtos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Gestão-Produtos` DEFAULT CHARACTER SET utf8 ;
USE `Gestão-Produtos` ;

-- -----------------------------------------------------
-- Table `Gestão-Produtos`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestão-Produtos`.`Produtos` (
  `Produtos_id` INT NOT NULL AUTO_INCREMENT,
  `Produtos_nome` VARCHAR(45) NULL,
  `Produtos_preco` DOUBLE NULL,
  `Produtos_categoria` VARCHAR(45) NULL,
  `Produtos_descricao` VARCHAR(200) NULL,
  `Produtos_desconto` DECIMAL(5,2) NULL,
  PRIMARY KEY (`Produtos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestão-Produtos`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestão-Produtos`.`Funcionarios` (
  `Funcionarios_id` INT NOT NULL,
  `Funcionarios_nome` VARCHAR(45) NULL,
  `Funcionarios_tempoAcesso` TIME NULL,
  `Funcionarios_cargo` VARCHAR(45) NULL,
  PRIMARY KEY (`Funcionarios_id`),
  UNIQUE INDEX `Funcionarios_id_UNIQUE` (`Funcionarios_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestão-Produtos`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestão-Produtos`.`Empresa` (
  `Empresa_id` INT NOT NULL,
  `Empresa_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Empresa_id`),
  UNIQUE INDEX `Empresa_nome_UNIQUE` (`Empresa_nome` ASC) VISIBLE,
  UNIQUE INDEX `Empresa_id_UNIQUE` (`Empresa_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestão-Produtos`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestão-Produtos`.`Pedidos` (
  `Pedidos_id` INT NOT NULL AUTO_INCREMENT,
  `Pedidos_nome` VARCHAR(45) NULL,
  `Pedidos_dataInicial` DATE NULL,
  `Pedidos_dataEntrega` DATE NULL,
  `Pedidos_descricao` VARCHAR(200) NULL,
  `Empresa_Empresa_id` INT NOT NULL,
  `Produtos_Produtos_id` INT NOT NULL,
  `Funcionarios_Funcionarios_id` INT NOT NULL,
  PRIMARY KEY (`Pedidos_id`),
  INDEX `fk_Pedidos_Empresa1_idx` (`Empresa_Empresa_id` ASC) VISIBLE,
  INDEX `fk_Pedidos_Produtos1_idx` (`Produtos_Produtos_id` ASC) VISIBLE,
  UNIQUE INDEX `Pedidos_id_UNIQUE` (`Pedidos_id` ASC) VISIBLE,
  INDEX `fk_Pedidos_Funcionarios1_idx` (`Funcionarios_Funcionarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedidos_Empresa1`
    FOREIGN KEY (`Empresa_Empresa_id`)
    REFERENCES `Gestão-Produtos`.`Empresa` (`Empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Produtos1`
    FOREIGN KEY (`Produtos_Produtos_id`)
    REFERENCES `Gestão-Produtos`.`Produtos` (`Produtos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedidos_Funcionarios1`
    FOREIGN KEY (`Funcionarios_Funcionarios_id`)
    REFERENCES `Gestão-Produtos`.`Funcionarios` (`Funcionarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestão-Produtos`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestão-Produtos`.`Login` (
  `Login_senha` VARCHAR(45) NOT NULL,
  `Login_Usuario` VARCHAR(45) NOT NULL,
  `Funcionarios_Funcionarios_id` INT NOT NULL,
  PRIMARY KEY (`Login_senha`, `Login_Usuario`, `Funcionarios_Funcionarios_id`),
  INDEX `fk_Login_Funcionarios1_idx` (`Funcionarios_Funcionarios_id` ASC) VISIBLE,
  UNIQUE INDEX `Funcionarios_Funcionarios_id_UNIQUE` (`Funcionarios_Funcionarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Funcionarios1`
    FOREIGN KEY (`Funcionarios_Funcionarios_id`)
    REFERENCES `Gestão-Produtos`.`Funcionarios` (`Funcionarios_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Gestão-Produtos`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Gestão-Produtos`.`Estoque` (
  `estoque_total` INT NOT NULL,
  `estoque_disponivel` INT NOT NULL,
  `Produtos_Produtos_id` INT NOT NULL,
  PRIMARY KEY (`estoque_total`, `estoque_disponivel`),
  INDEX `fk_Estoque_Produtos1_idx` (`Produtos_Produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estoque_Produtos1`
    FOREIGN KEY (`Produtos_Produtos_id`)
    REFERENCES `Gestão-Produtos`.`Produtos` (`Produtos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
